### ISSUE TITLE
Issue with setting image name with example 5

### ISSUE THREAD

**Issue by antmedellin** [cubert-hyperspectral/cuvis.cpp.examples#4]
I addeded the following on this [example](https://github.com/cubert-hyperspectral/cuvis.cpp.examples/blob/main/05_recordSingleImages_cpp/main.cpp) to line 71 to try and set the name of the file being saved, but the saved file is still "Auto_001.cu3s". I also tried adding the .cu3s extension to the string and did not have an effect. What is the proper way to set the name of the file for saving?

`mesu.set_name("test");`

**Comment by robertCubert** [comment]
If you use the exporter to save your measurements, you would need to do it this way: 

```
  auto session = cuvis::SessionInfo();
  session.name = "Test";
  acq.set_session_info(session);
```

You can also change the name in the mesu if you save it without an export context: 

```
      mesu.set_name("Test");
      mesu.save(saveArgs);
```
